/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mjj;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/**
 *
 * @author Asus
 */
public class Food extends javax.swing.JFrame {

    /**
     * Creates new form Catalog
     */
    JFrame frame;
    public Food() {
        initComponents();
        String [] cols = {"ID", "Name", "Quantity", "Per Price", "Status","Type"};
        DefaultTableModel modal = new DefaultTableModel(null, cols);
        FoodTable.setModel(modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPerPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboAvailable = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cboType = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FoodTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Food System"));
        jPanel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 10, 2));

        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jPanel1.add(txtID);

        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jPanel1.add(txtName);

        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4);
        jPanel1.add(txtQuantity);

        jLabel5.setText("Per Price");
        jPanel1.add(jLabel5);

        txtPerPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerPriceActionPerformed(evt);
            }
        });
        jPanel1.add(txtPerPrice);

        jLabel6.setText("Status");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6);

        cboAvailable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Non Available" }));
        cboAvailable.setSelectedIndex(-1);
        jPanel1.add(cboAvailable);

        jLabel7.setText("Type");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7);

        cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food", "Drink" }));
        cboType.setSelectedIndex(-1);
        jPanel1.add(cboType);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setLayout(new java.awt.GridLayout(1, 4, 10, 10));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        FoodTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FoodTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FoodTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(FoodTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        boolean isValid = validation();    
        if(isValid == false){
            return;
        }else{
            String ID = txtID.getText();
            String name = txtName.getText();
            int quantity = Integer.parseInt(txtQuantity.getText());
            double price = Double.parseDouble(txtPerPrice.getText());
            String available = cboAvailable.getSelectedItem().toString();
            String type = cboType.getSelectedItem().toString();
            if(FoodTable.getRowCount()> -1){
                for(int i=0; i<FoodTable.getRowCount(); i++){
                    String id = FoodTable.getValueAt(i, 1).toString();
                    if(ID.equals(id)){
                        JOptionPane.showMessageDialog(frame, "ID must be unique!", "Error", JOptionPane.ERROR_MESSAGE );
                        return;
                    }
                }
            }
            
            DefaultTableModel model = (DefaultTableModel) FoodTable.getModel();
            model.addRow(new Object[]{ID, name, quantity, price, available,type});
            JOptionPane.showMessageDialog(frame, "Added Success!", "Added Success", JOptionPane.INFORMATION_MESSAGE );
            clear();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void FoodTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FoodTableMouseClicked
        int index  = FoodTable.getSelectedRow();
        TableModel model = FoodTable.getModel();
        String id = model.getValueAt(index, 0).toString();
        String name = model.getValueAt(index, 1).toString();
        String quantity = model.getValueAt(index, 2).toString();
        String price = model.getValueAt(index, 3).toString();
        String available = model.getValueAt(index, 4).toString();
        
        txtID.setText(id);
        txtID.setEnabled(false);
        txtName.setText(name);
        txtQuantity.setText(quantity);
        txtPerPrice.setText(price);
        cboAvailable.setSelectedItem(available);
        btnAdd.setEnabled(false);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(true);
    }//GEN-LAST:event_FoodTableMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        boolean isValid = validation();    
        if(isValid == false){
            return;
        }else{
            for(int i=0; i<FoodTable.getRowCount(); i++){
                String id = FoodTable.getValueAt(i, 0).toString();
                    if(txtID.getText().equals(id)){
                        String ID = txtID.getText();
                        String name = txtName.getText();
                        int quantity = Integer.parseInt(txtQuantity.getText());
                        double price = Double.parseDouble(txtPerPrice.getText());
                        String available = cboAvailable.getSelectedItem().toString();
                        String type = cboType.getSelectedItem().toString();
                        
                        FoodTable.setValueAt(name,i,1);
                        FoodTable.setValueAt(quantity,i,2);
                        FoodTable.setValueAt(price,i,3);
                        FoodTable.setValueAt(available,i,4);
                        FoodTable.setValueAt(type, i, 5);
                        JOptionPane.showMessageDialog(frame, "Updated Success!", "Updated Success", JOptionPane.INFORMATION_MESSAGE );
                        break;
                    }
            }
            clear();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtPerPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerPriceActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int dt = FoodTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) FoodTable.getModel();
        
        boolean isValid = validation();    
        if(isValid == false){
            return;
        }else{
            String ID = txtID.getText();
            String name = txtName.getText();
            int quantity = Integer.parseInt(txtQuantity.getText());
            double price = Double.parseDouble(txtPerPrice.getText());
            String available = cboAvailable.getSelectedItem().toString();
            String type = cboType.getSelectedItem().toString();
            if(dt>=0){
            model.removeRow(dt);
            JOptionPane.showMessageDialog(frame, "Deleted Success!", "Deleted Success", JOptionPane.INFORMATION_MESSAGE );            
             }
        }
        
        txtID.setText("") ;
        txtName.setText("");
        txtQuantity.setText("");
        txtPerPrice.setText("");
        cboAvailable.setSelectedIndex(-1);
        cboType.setSelectedIndex(-1);
        txtID.setEnabled(true);
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Food.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Food().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FoodTable;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cboAvailable;
    private javax.swing.JComboBox<String> cboType;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPerPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private boolean validation() {
        boolean isValid = true;
        String error = "";
        if(txtID.getText().length()<=0){
            isValid = false;
            error += "ID is required!\n";
        }else{
            try{
                int id = Integer.parseInt(txtID.getText());
            }catch(NumberFormatException ex){
                isValid = false;
                error += "Id must be in Number";
            }
        }
        if(txtName.getText().length()<=0){
            isValid = false;
            error += "Name is required!\n";
        }
        if(txtQuantity.getText().length() <= 0){
            isValid = false;
            error += "Quantity is required!\n";
        }else{
            try{
                int quantity = Integer.parseInt(txtQuantity.getText());
                if(quantity <= 0){
                    isValid = false;
                    error += "Quantity must bigger than 0!\n";
                }
            }catch(NumberFormatException ex){
                isValid = false;
                error += "Quantity must be an integer";
            }
        }
        if(txtPerPrice.getText().length() <= 0){
            isValid = false;
            error += "Per Price is required!\n";
        }else{
            try{
                double price = Double.parseDouble(txtPerPrice.getText());
                if(price <= 0){
                    isValid = false;
                    error += "Per Price must bigger than 0!\n";
                }
            }catch(NumberFormatException ex){
                isValid = false;
                error += "Per Price must be an integer";
            }
        }
        if(cboAvailable.getSelectedIndex() == -1){
            isValid= false;
            error += "Available is required!\n";
        }
        if(cboType.getSelectedIndex() == -1){
            isValid= false;
            error += "Type is required!\n";
        }
        if(isValid == false){
            JOptionPane.showMessageDialog(frame, error, "Error", JOptionPane.ERROR_MESSAGE );
        }
        return isValid;
    }

    private void clear() {
        txtID.setText("") ;
        txtName.setText("");
        txtQuantity.setText("");
        txtPerPrice.setText("");
        cboAvailable.setSelectedIndex(-1);
        cboType.setSelectedIndex(-1);
        txtID.setEnabled(true);
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(false);
        btnDelete.setEnabled(false);
    }
}
